# Use a imagem base PHP com Apache
FROM php:7.4-apache

# Instale as dependências necessárias para o Dompdf
RUN apt-get update && apt-get install -y \
    libfontconfig1 \
    libjpeg62-turbo-dev \
    libpng-dev \
    libzip-dev \
    zip \
    unzip

# Instale as extensões PHP necessárias
RUN docker-php-ext-install \
    gd \
    zip

# Copie os arquivos do projeto para o diretório de trabalho do Apache
COPY . /var/www/html/

# Defina o diretório de trabalho como o diretório do Apache
WORKDIR /var/www/html/

# Instale as dependências do Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Execute o Composer para instalar as dependências
RUN composer install --no-dev --optimize-autoloader

# Exponha a porta 80 para acesso HTTP
EXPOSE 80

# Inicie o servidor Apache ao iniciar o contêiner
CMD ["apache2-foreground"]
